# ===========================================================================
# BLUEPRINT: Nachtmodus Auto-Ausschalt
# ===========================================================================
# Voraussetzung: Die Helfer aus "helfer.yaml" m端ssen vorher erstellt werden.
# ===========================================================================

blueprint:
  name: Nachtmodus Auto-Ausschalt
  description: >
    Schaltet den Nachtmodus jeden Morgen automatisch wieder aus,
    damit er nicht "vergessen" bleibt. Die Uhrzeit wird 端ber einen
    Helfer im Dashboard steuerbar gemacht.
  domain: automation
  input:
    nachtmodus_toggle:
      name: Nachtmodus-Toggle
      description: Der input_boolean f端r den Nachtmodus (aus helfer.yaml).
      selector:
        entity:
          domain: input_boolean

    nachtmodus_ausschalt_uhrzeit:
      name: Nachtmodus Ausschalt-Uhrzeit (Helfer)
      description: >
        Der input_datetime-Helfer f端r die Ausschalt-Uhrzeit (aus helfer.yaml).
      selector:
        entity:
          domain: input_datetime

trigger:
  - platform: template
    value_template: >
      {{ now().strftime('%H:%M') == states('input_datetime.schlafzimmer_nachtmodus_ausschalt_uhrzeit') }}
    for:
      seconds: 0

condition:
  - condition: state
    entity_id: !input nachtmodus_toggle
    state: "on"

action:
  - service: input_boolean.turn_off
    target:
      entity_id: !input nachtmodus_toggle
