# ===========================================================================
# BLUEPRINT: Nachtmodus Auto-Ausschaltung an Werktagen
# ===========================================================================
# 
# ===========================================================================

blueprint:
  name: Nachtmodus Auto-Ausschalt (Werktag)
  description: >
    Schaltet den Nachtmodus an Werktagen zu einer festen Zeit aus.
  domain: automation
  input:
    nachtmodus_toggle:
      name: Nachtmodus-Toggle
      selector:
        entity:
          domain: input_boolean
    
    workday_sensor:
      name: Arbeitstag-Sensor
      selector:
        entity:
          domain: binary_sensor
    
    ausschalt_zeit:
      name: Ausschalt-Zeit (Werktag)
      default: "06:20:00"
      selector:
        time: {}

trigger:
  - platform: time
    at: !input ausschalt_zeit

condition:
  - condition: state
    entity_id: !input nachtmodus_toggle
    state: "on"
  
  - condition: state
    entity_id: !input workday_sensor
    state: "on"

action:
  - service: input_boolean.turn_off
    target:
      entity_id: !input nachtmodus_toggle
